apiVersion: v1
kind: PersistentVolumeClaim
{{ $existingPvc := lookup "v1" "PersistentVolumeClaim" .Release.Namespace "userservice-report" }}
{{ $storageClass := .Values.global.storageClass }}
{{ if $existingPvc }}
{{ $storageClass = $existingPvc.spec.storageClassName | default "" }}
{{ end }}
metadata:
  labels:
    app: userservice-report
  name: userservice-report
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  {{- if $storageClass }}
  storageClassName: {{ $storageClass | quote }}
  {{- end }}
