apiVersion: batch/v1
kind: Job
metadata:
  name: create-mongo-users
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: wait-for-mongo-ready
          image: mongo:6.0
          env:
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: MONGO_INITDB_ROOT_USERNAME
                  name: mongodb-secret
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MONGO_INITDB_ROOT_PASSWORD
                  name: mongodb-secret
          command:
            - sh
            - -c
            - |
              until mongosh --username "$MONGODB_USERNAME" --password "$MONGODB_PASSWORD" --authenticationDatabase admin --eval "db.adminCommand('ping')" mongodb.{{ .Release.Namespace }}:27017; do
                echo "waiting for mongodb auth to work";
                sleep 2;
              done
      containers:
        - name: create-mongo-users
          image: {{ .Values.imageName }}:{{ .Values.imageVersion }}
          env:
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: MONGO_INITDB_ROOT_USERNAME
                  name: mongodb-secret
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MONGO_INITDB_ROOT_PASSWORD
                  name: mongodb-secret
            - name: MONGO_NOSQLCLIENT_USER
              valueFrom:
                secretKeyRef:
                  key: MONGO_NOSQLCLIENT_USER
                  name: mongodb-secret
            - name: MONGO_NOSQLCLIENT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MONGO_NOSQLCLIENT_PASSWORD
                  name: mongodb-secret
            - name: MONGO_STATISTICS_USER
              valueFrom:
                secretKeyRef:
                  key: MONGO_STATISTICS_USER
                  name: mongodb-secret
            - name: MONGO_STATISTICS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MONGO_STATISTICS_PASSWORD
                  name: mongodb-secret
            - name: MONGO_CONSULTING_TYPES_USER
              valueFrom:
                secretKeyRef:
                  key: MONGO_CONSULTING_TYPES_USER
                  name: mongodb-secret
            - name: MONGO_CONSULTING_TYPES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MONGO_CONSULTING_TYPES_PASSWORD
                  name: mongodb-secret
            - name: MONGO_ROCKETCHAT_USER
              valueFrom:
                secretKeyRef:
                  key: MONGO_ROCKETCHAT_USER
                  name: mongodb-secret
            - name: MONGO_ROCKETCHAT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MONGO_ROCKETCHAT_PASSWORD
                  name: mongodb-secret
          command:
            - /bin/bash
            - -c
            - |
              set -e;
              mongo_host="mongodb.{{ .Release.Namespace }}:27017";
              create_or_update_user() {
                local db_name="$1";
                local user_name="$2";
                local password="$3";
                echo "Ensuring Mongo user: ${user_name} on ${db_name}";
                mongosh "$mongo_host" --username "$MONGODB_USERNAME" --password "$MONGODB_PASSWORD" --authenticationDatabase admin --eval "db=db.getSiblingDB('${db_name}'); if (db.getUser('${user_name}')) { db.updateUser('${user_name}', { pwd: '${password}', roles: [{ role: 'readWrite', db: '${db_name}' }]}); } else { db.createUser({ user: '${user_name}', pwd: '${password}', roles: [{ role: 'readWrite', db: '${db_name}' }]}); }"
              }
              create_or_update_user "nosqlclient" "$MONGO_NOSQLCLIENT_USER" "$MONGO_NOSQLCLIENT_PASSWORD";
              create_or_update_user "statistics" "$MONGO_STATISTICS_USER" "$MONGO_STATISTICS_PASSWORD";
              create_or_update_user "consulting_types" "$MONGO_CONSULTING_TYPES_USER" "$MONGO_CONSULTING_TYPES_PASSWORD";
              create_or_update_user "rocketchat" "$MONGO_ROCKETCHAT_USER" "$MONGO_ROCKETCHAT_PASSWORD";
  backoffLimit: 1
