apiVersion: v1
kind: PersistentVolumeClaim
{{ $existingPvc := lookup "v1" "PersistentVolumeClaim" .Release.Namespace "redis-pvc" }}
{{ $storageClass := .Values.global.storageClass }}
{{ if $existingPvc }}
{{ $storageClass = $existingPvc.spec.storageClassName | default "" }}
{{ end }}
metadata:
  name: redis-pvc
  labels:
    app: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  {{- if $storageClass }}
  storageClassName: {{ $storageClass | quote }}
  {{- end }}
