apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-reconcile-smtp-script
  namespace: {{ .Release.Namespace }}
data:
  keycloak-reconcile-smtp.py: |
    {{- .Files.Get "files/keycloak-reconcile-smtp.py" | nindent 4 }}
