apiVersion: apps/v1
kind: Deployment
metadata:
{{- with include "oriso.runtimeAnnotations" . }}
  annotations:
{{ . | nindent 4 }}
{{- end }}
  name: livekit
  namespace: {{ .Release.Namespace }}
  labels:
    app: livekit
spec:
  replicas: {{ .Values.livekit.replicas }}
  selector:
    matchLabels:
      app: livekit
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        app: livekit
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: livekit
              topologyKey: kubernetes.io/hostname
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      enableServiceLinks: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 18000
      containers:
        - name: livekit
          image: {{ include "oriso.immutableImage" (list "livekit.image" .Values.livekit.image) | quote }}
          imagePullPolicy: IfNotPresent
          args:
            - --config
            - /etc/livekit/config.yaml
          ports:
            - containerPort: 7880
              name: http
              protocol: TCP
          volumeMounts:
            - name: livekit-config
              mountPath: /etc/livekit
      volumes:
        - name: livekit-config
          secret:
            secretName: {{ .Values.livekit.existingConfigSecret.name | quote }}
            items:
              - key: {{ .Values.livekit.existingConfigSecret.key | quote }}
                path: config.yaml
