apiVersion: v1
kind: Secret
metadata:
  name: livekit-config
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  config.yaml: |
    port: 7880
    rtc:
      tcp_port: 7881
      port_range_start: 50000
      port_range_end: 50100
      use_external_ip: true
    room:
      auto_create: false
    keys:
      {{ required "livekit.api.key is required" .Values.livekit.api.key }}: {{ required "livekit.api.secret is required" .Values.livekit.api.secret }}
    webhook:
      api_key: {{ required "livekit.api.key is required" .Values.livekit.api.key }}
      urls:
        - http://matrixrtc-authorization-service:8080/sfu_webhook
