apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: livekit
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: livekit
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: matrixrtc-auth-policy-gateway
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: matrixrtc-auth-policy-gateway
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: matrixrtc-authorization-service
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: matrixrtc-authorization-service
